#!/bin/bash
# shellcheck disable=all

HERE="$(dirname "$(realpath "$0")")"
cd $HERE

viewer="more"
version=${1:-5.4}

if [[ "$EDITOR" != "" ]] && [[ -f "$EDITOR" ]]; then
  viewer="$EDITOR"
elif [[ "$(whereis nvim | cut -d: -f2-)" != "" ]];then
  viewer="nvim -R "
elif [[ "$(whereis vim | cut -d: -f2-)" != "" ]];then
  viewer="vim -R"
elif [[ "$(whereis bat | cut -d: -f2-)" != "" ]]; then
  viewer="bat"
elif [[ "$(whereis less | cut -d: -f2-)" != "" ]]; then
  viewer="less"
fi


if [[ -f "lua-${version}-manual.md" ]]; then
  $viewer "lua-${version}-manual.md";

# Just for clarification:
# If user try --help -help -h or anything else always will default to usage
else
  echo Run:
  echo manlua VERSION
  echo
  echo Where VERSION is one of these:
  ls lua*manual.md | cut -d- -f2
fi

